-- !!! Do not edit this file!!! You could corrupt its exact structure
-- that is compiled by Quartus into M9K memory ROM blocks.
-- CTU-FEE in Prague, Dept. of Control Eng. [Richard Susta]
-- FPGA-LCD Utils generated file on 05/22/2026 01:51:11
-- from bitmap file /home/pavel/skola/LS_2026_vyuka/lsp/lcd/ridici_panel/project_main/bitmaps/E.bmp
-- adjusted to the sizes: Width x Height= 32x32=1024 [0x400] pixels.
-- 4096 [0x1000] bit memory is arranged for an 10-bit address bus reading a 4-bit data output.
-- The color palette in the index order as std_logic_vector(23 downto 0) items:
-- X"000000",  X"737173",  X"7B7D7B",  X"848684",  X"8C8A8C",  X"9CA29C",  X"ADAAAD",  X"DEDFDE"  -- 0 to 7
-- X"FFFFFF",  X"181C18"  -- 8 to 9

library ieee, work; use ieee.std_logic_1164.all; use ieee.numeric_std.all;
entity E is
port ( address: in std_logic_vector(9 downto 0):=(others=>'0');
       clock: in std_logic:= '1';
       q: out std_logic_vector(3 downto 0):=(others=>'0'));
end entity;

architecture rtl of E is
  type arr_t is array(0 to 2**address'LENGTH-1) of std_logic_vector(q'RANGE);
  constant arr :arr_t:=(
 0 to 37=>"1000", 38=>"0101", 39 to 55=>"0000", 56=>"1001", 57 to 69=>"1000",
 70=>"0101", 71 to 87=>"0000", 88=>"1001", 89 to 101=>"1000", 102=>"0101", 103 to 119=>"0000", 120=>"1001", 121 to 133=>"1000",
 134=>"0101", 135 to 151=>"0000", 152=>"1001", 153 to 165=>"1000", 166=>"0101", 167 to 171=>"0000", 172=>"0001", 173 to 183=>"0011",
 184=>"0100", 185 to 197=>"1000", 198=>"0101", 199 to 203=>"0000", 204=>"0111", 205 to 229=>"1000", 230=>"0101", 231 to 235=>"0000",
 236=>"0111", 237 to 261=>"1000", 262=>"0101", 263 to 267=>"0000", 268=>"0111", 269 to 293=>"1000", 294=>"0101", 295 to 299=>"0000",
 300=>"0111", 301 to 325=>"1000", 326=>"0101", 327 to 331=>"0000", 332=>"0111", 333 to 357=>"1000", 358=>"0101", 359 to 363=>"0000",
 364=>"0111", 365 to 389=>"1000", 390=>"0101", 391 to 395=>"0000", 396=>"0111", 397 to 421=>"1000", 422=>"0101", 423 to 438=>"0000",
 439=>"0010", 440 to 453=>"1000", 454=>"0101", 455 to 470=>"0000", 471=>"0010", 472 to 485=>"1000", 486=>"0101", 487 to 502=>"0000",
 503=>"0010", 504 to 517=>"1000", 518=>"0101", 519 to 534=>"0000", 535=>"0010", 536 to 549=>"1000", 550=>"0101", 551 to 555=>"0000",
 556=>"0001", 557 to 566=>"0011", 567=>"0110", 568 to 581=>"1000", 582=>"0101", 583 to 587=>"0000", 588=>"0111", 589 to 613=>"1000",
 614=>"0101", 615 to 619=>"0000", 620=>"0111", 621 to 645=>"1000", 646=>"0101", 647 to 651=>"0000", 652=>"0111", 653 to 677=>"1000",
 678=>"0101", 679 to 683=>"0000", 684=>"0111", 685 to 709=>"1000", 710=>"0101", 711 to 715=>"0000", 716=>"0111", 717 to 741=>"1000",
 742=>"0101", 743 to 747=>"0000", 748=>"0111", 749 to 773=>"1000", 774=>"0101", 775 to 779=>"0000", 780=>"0111", 781 to 805=>"1000",
 806=>"0101", 807 to 811=>"0000", 812=>"0111", 813 to 837=>"1000", 838=>"0101", 839 to 843=>"0000", 844=>"0001", 845 to 855=>"0011",
 856=>"0100", 857 to 869=>"1000", 870=>"0101", 871 to 887=>"0000", 888=>"1001", 889 to 901=>"1000", 902=>"0101", 903 to 919=>"0000",
 920=>"1001", 921 to 933=>"1000", 934=>"0101", 935 to 951=>"0000", 952=>"1001", 953 to 965=>"1000", 966=>"0101", 967 to 983=>"0000",
 984=>"1001", others=>"1000");
-------------------------------------------------------
begin
  process(clock)
  variable ix:integer range 0 to 2**address'LENGTH-1:=0;
  begin
      if rising_edge(clock) then
          ix:= to_integer(unsigned(address));
          q <= arr(ix);
      end if;
  end process;
end architecture;