-- !!! Do not edit this file!!! You could corrupt its exact structure
-- that is compiled by Quartus into M9K memory ROM blocks.
-- CTU-FEE in Prague, Dept. of Control Eng. [Richard Susta]
-- FPGA-LCD Utils generated file on 05/22/2026 01:51:18
-- from bitmap file /home/pavel/skola/LS_2026_vyuka/lsp/lcd/ridici_panel/project_main/bitmaps/I.bmp
-- adjusted to the sizes: Width x Height= 32x32=1024 [0x400] pixels.
-- 4096 [0x1000] bit memory is arranged for an 10-bit address bus reading a 4-bit data output.
-- The color palette in the index order as std_logic_vector(23 downto 0) items:
-- X"000000",  X"525552",  X"737173",  X"848684",  X"A5A6A5",  X"ADAEAD",  X"C6C7C6",  X"D6DBD6"  -- 0 to 7
-- X"DEE3DE",  X"E7EBE7",  X"FFFFFF"  -- 8 to 10

library ieee, work; use ieee.std_logic_1164.all; use ieee.numeric_std.all;
entity I is
port ( address: in std_logic_vector(9 downto 0):=(others=>'0');
       clock: in std_logic:= '1';
       q: out std_logic_vector(3 downto 0):=(others=>'0'));
end entity;

architecture rtl of I is
  type arr_t is array(0 to 2**address'LENGTH-1) of std_logic_vector(q'RANGE);
  constant arr :arr_t:=(
 0 to 37=>"1010", 38=>"0101", 39 to 55=>"0000", 56=>"1000", 57 to 69=>"1010", 70=>"0101", 71 to 87=>"0000",
 88=>"1000", 89 to 101=>"1010", 102=>"0101", 103 to 119=>"0000", 120=>"1000", 121 to 133=>"1010", 134=>"0101", 135 to 151=>"0000",
 152=>"1000", 153 to 165=>"1010", 166=>"0110", 167 to 171=>"0011", 172=>"0001", 173 to 177=>"0000", 178=>"0010", 179 to 183=>"0011",
 184=>"1001", 185 to 203=>"1010", 204=>"0100", 205 to 209=>"0000", 210=>"0111", 211 to 235=>"1010", 236=>"0100", 237 to 241=>"0000",
 242=>"0111", 243 to 267=>"1010", 268=>"0100", 269 to 273=>"0000", 274=>"0111", 275 to 299=>"1010", 300=>"0100", 301 to 305=>"0000",
 306=>"0111", 307 to 331=>"1010", 332=>"0100", 333 to 337=>"0000", 338=>"0111", 339 to 363=>"1010", 364=>"0100", 365 to 369=>"0000",
 370=>"0111", 371 to 395=>"1010", 396=>"0100", 397 to 401=>"0000", 402=>"0111", 403 to 427=>"1010", 428=>"0100", 429 to 433=>"0000",
 434=>"0111", 435 to 459=>"1010", 460=>"0100", 461 to 465=>"0000", 466=>"0111", 467 to 491=>"1010", 492=>"0100", 493 to 497=>"0000",
 498=>"0111", 499 to 523=>"1010", 524=>"0100", 525 to 529=>"0000", 530=>"0111", 531 to 555=>"1010", 556=>"0100", 557 to 561=>"0000",
 562=>"0111", 563 to 587=>"1010", 588=>"0100", 589 to 593=>"0000", 594=>"0111", 595 to 619=>"1010", 620=>"0100", 621 to 625=>"0000",
 626=>"0111", 627 to 651=>"1010", 652=>"0100", 653 to 657=>"0000", 658=>"0111", 659 to 683=>"1010", 684=>"0100", 685 to 689=>"0000",
 690=>"0111", 691 to 715=>"1010", 716=>"0100", 717 to 721=>"0000", 722=>"0111", 723 to 747=>"1010", 748=>"0100", 749 to 753=>"0000",
 754=>"0111", 755 to 779=>"1010", 780=>"0100", 781 to 785=>"0000", 786=>"0111", 787 to 811=>"1010", 812=>"0100", 813 to 817=>"0000",
 818=>"0111", 819 to 837=>"1010", 838=>"0110", 839 to 843=>"0011", 844=>"0001", 845 to 849=>"0000", 850=>"0010", 851 to 855=>"0011",
 856=>"1001", 857 to 869=>"1010", 870=>"0101", 871 to 887=>"0000", 888=>"1000", 889 to 901=>"1010", 902=>"0101", 903 to 919=>"0000",
 920=>"1000", 921 to 933=>"1010", 934=>"0101", 935 to 951=>"0000", 952=>"1000", 953 to 965=>"1010", 966=>"0101", 967 to 983=>"0000",
 984=>"1000", others=>"1010");
-------------------------------------------------------
begin
  process(clock)
  variable ix:integer range 0 to 2**address'LENGTH-1:=0;
  begin
      if rising_edge(clock) then
          ix:= to_integer(unsigned(address));
          q <= arr(ix);
      end if;
  end process;
end architecture;