#!/usr/bin/env python3
"""Generate an MMC5883MA I2C example trace for PulseView.

The generated trace is synthetic: it shows the transactions produced by the
project driver, not a capture from real hardware.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


class DigitalTrace:
    def __init__(self, sample_rate_hz: int, half_period_us: int) -> None:
        self.sample_rate_hz = sample_rate_hz
        self.half_period_us = half_period_us
        self.time_us = 0
        self.scl = 1
        self.sda = 1
        self.events: list[tuple[int, int, int]] = [(0, self.scl, self.sda)]

    def _set(self, *, scl: int | None = None, sda: int | None = None) -> None:
        if scl is not None:
            self.scl = scl
        if sda is not None:
            self.sda = sda
        if self.events[-1] != (self.time_us, self.scl, self.sda):
            self.events.append((self.time_us, self.scl, self.sda))

    def wait(self, us: int) -> None:
        self.time_us += us

    def idle(self, us: int = 20) -> None:
        self._set(scl=1, sda=1)
        self.wait(us)

    def start(self) -> None:
        if self.scl == 0:
            self._set(sda=1)
            self.wait(self.half_period_us)
            self._set(scl=1)
        else:
            self._set(scl=1, sda=1)
        self.wait(self.half_period_us)
        self._set(sda=0)
        self.wait(self.half_period_us)
        self._set(scl=0)
        self.wait(self.half_period_us)

    def stop(self) -> None:
        self._set(scl=0, sda=0)
        self.wait(self.half_period_us)
        self._set(scl=1)
        self.wait(self.half_period_us)
        self._set(sda=1)
        self.wait(self.half_period_us)

    def bit(self, value: int) -> None:
        self._set(scl=0, sda=value)
        self.wait(self.half_period_us)
        self._set(scl=1)
        self.wait(self.half_period_us)
        self._set(scl=0)
        self.wait(self.half_period_us)

    def byte(self, value: int, ack: int = 0) -> None:
        for bit_index in range(7, -1, -1):
            self.bit((value >> bit_index) & 1)
        self.bit(ack)


def write_register(trace: DigitalTrace, register: int, value: int) -> None:
    trace.start()
    trace.byte(0x60)      # 7-bit address 0x30, write
    trace.byte(register)
    trace.byte(value)
    trace.stop()
    trace.idle()


def read_register(trace: DigitalTrace, register: int, value: int) -> None:
    trace.start()
    trace.byte(0x60)      # 7-bit address 0x30, write register pointer
    trace.byte(register)
    trace.start()         # repeated START
    trace.byte(0x61)      # 7-bit address 0x30, read
    trace.byte(value, ack=1)  # master NACKs the single read byte
    trace.stop()
    trace.idle()


def read_measurement(trace: DigitalTrace, data: list[int]) -> None:
    trace.start()
    trace.byte(0x60)      # 7-bit address 0x30, write register pointer
    trace.byte(0x00)      # Xout low, auto-increment through Zout high
    trace.start()         # repeated START
    trace.byte(0x61)      # 7-bit address 0x30, read
    for index, value in enumerate(data):
        trace.byte(value, ack=1 if index == len(data) - 1 else 0)
    trace.stop()
    trace.idle()


def generate_trace(sample_rate_hz: int, i2c_hz: int) -> DigitalTrace:
    half_period_us = round(1_000_000 / (i2c_hz * 2))
    trace = DigitalTrace(sample_rate_hz, half_period_us)
    trace.idle(50)

    # MMC5883L::init() is called by the constructor and again from main().
    for _ in range(2):
        write_register(trace, 0x08, 0x08)  # Internal Control 0: SET pulse
        write_register(trace, 0x09, 0x00)  # Internal Control 1: BW=00, 16-bit/100Hz mode
        write_register(trace, 0x0A, 0x00)  # Internal Control 2: continuous mode off
        trace.idle(100)

    # One call to compass.getHeadingXY(data).
    write_register(trace, 0x08, 0x01)      # Internal Control 0: TM_M, start magnetic measurement
    read_register(trace, 0x07, 0x00)       # Status: measurement not done yet
    read_register(trace, 0x07, 0x01)       # Status: Meas_M_Done=1

    # Example raw bytes: X low/high, Y low/high, Z low/high.
    read_measurement(trace, [0x34, 0x92, 0x10, 0x81, 0xE0, 0x7C])

    trace.idle(50)
    return trace


def write_vcd(path: Path, trace: DigitalTrace) -> None:
    lines = [
        "$date generated by generate_mmc5883_i2c_trace.py $end",
        "$version synthetic MMC5883MA I2C trace $end",
        "$timescale 1 us $end",
        "$scope module logic $end",
        "$var wire 1 c SCL $end",
        "$var wire 1 d SDA $end",
        "$upscope $end",
        "$enddefinitions $end",
        "$dumpvars",
        "1c",
        "1d",
        "$end",
    ]

    last_time = None
    for time_us, scl, sda in trace.events:
        if time_us != last_time:
            lines.append(f"#{time_us}")
            last_time = time_us
        lines.append(f"{scl}c")
        lines.append(f"{sda}d")

    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_csv(path: Path, trace: DigitalTrace) -> None:
    sample_period_us = 1_000_000 / trace.sample_rate_hz
    total_samples = int(trace.time_us / sample_period_us) + 1

    event_index = 0
    scl = trace.events[0][1]
    sda = trace.events[0][2]

    with path.open("w", encoding="ascii", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["time_us", "SCL", "SDA"])
        for sample in range(total_samples):
            time_us = round(sample * sample_period_us, 6)
            while (
                event_index + 1 < len(trace.events)
                and trace.events[event_index + 1][0] <= time_us
            ):
                event_index += 1
                _, scl, sda = trace.events[event_index]
            writer.writerow([time_us, scl, sda])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sample-rate", type=int, default=1_000_000)
    parser.add_argument("--i2c-rate", type=int, default=100_000)
    parser.add_argument("--out-dir", type=Path, default=Path(__file__).resolve().parent)
    args = parser.parse_args()

    trace = generate_trace(args.sample_rate, args.i2c_rate)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    write_vcd(args.out_dir / "mmc5883_i2c_example.vcd", trace)
    write_csv(args.out_dir / "mmc5883_i2c_example.csv", trace)

    print(f"Generated {args.out_dir / 'mmc5883_i2c_example.vcd'}")
    print(f"Generated {args.out_dir / 'mmc5883_i2c_example.csv'}")
    print(f"Duration: {trace.time_us} us")


if __name__ == "__main__":
    main()
