#!/usr/bin/env python3
"""Generate an SSD1306 software-SPI blink trace for PulseView.

The generated trace is synthetic: it shows only the two commands used by
main_example.cpp while the display background is blinking.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


class DigitalTrace:
    def __init__(self, sample_rate_hz: int, half_period_us: int) -> None:
        self.sample_rate_hz = sample_rate_hz
        self.half_period_us = half_period_us
        self.time_us = 0
        self.clk = 1
        self.mosi = 0
        self.dc = 0
        self.cs = 1
        self.events: list[tuple[int, int, int, int, int]] = [
            (0, self.clk, self.mosi, self.dc, self.cs)
        ]

    def _set(
        self,
        *,
        clk: int | None = None,
        mosi: int | None = None,
        dc: int | None = None,
        cs: int | None = None,
    ) -> None:
        if clk is not None:
            self.clk = clk
        if mosi is not None:
            self.mosi = mosi
        if dc is not None:
            self.dc = dc
        if cs is not None:
            self.cs = cs
        event = (self.time_us, self.clk, self.mosi, self.dc, self.cs)
        if self.events[-1] != event:
            self.events.append(event)

    def wait(self, us: int) -> None:
        self.time_us += us

    def idle(self, us: int) -> None:
        self._set(clk=1, cs=1)
        self.wait(us)

    def write_byte(self, value: int) -> None:
        # Matches SSD1306_mini_swspi::swspi_write(): data bit, CLK low, CLK high.
        for bit_index in range(7, -1, -1):
            bit = (value >> bit_index) & 1
            self._set(mosi=bit)
            self.wait(self.half_period_us)
            self._set(clk=0)
            self.wait(self.half_period_us)
            self._set(clk=1)
            self.wait(self.half_period_us)

    def command(self, value: int) -> None:
        # Matches SSD1306_mini_swspi::command(): CS high, DC low, CS low, byte, CS high.
        self._set(cs=1)
        self.wait(self.half_period_us)
        self._set(dc=0)
        self.wait(self.half_period_us)
        self._set(cs=0)
        self.wait(self.half_period_us)
        self.write_byte(value)
        self._set(cs=1)
        self.wait(self.half_period_us)


def generate_trace(sample_rate_hz: int, spi_hz: int, gap_ms: int) -> DigitalTrace:
    half_period_us = max(1, round(1_000_000 / (spi_hz * 2)))
    trace = DigitalTrace(sample_rate_hz, half_period_us)

    trace.idle(50)

    # main_example.cpp:
    #   gOled1.invertDisplay(0);  -> SSD1306_NORMALDISPLAY = 0xA6
    #   thread_sleep_for(500);
    #   gOled1.invertDisplay(1);  -> SSD1306_INVERTDISPLAY = 0xA7
    trace.command(0xA6)
    trace.idle(gap_ms * 1000)
    trace.command(0xA7)
    trace.idle(50)

    return trace


def write_vcd(path: Path, trace: DigitalTrace) -> None:
    lines = [
        "$date generated by generate_ssd1306_spi_blink_trace.py $end",
        "$version synthetic SSD1306 software-SPI blink trace $end",
        "$timescale 1 us $end",
        "$scope module logic $end",
        "$var wire 1 c CLK $end",
        "$var wire 1 m MOSI $end",
        "$var wire 1 d DC $end",
        "$var wire 1 s CS $end",
        "$upscope $end",
        "$enddefinitions $end",
        "$dumpvars",
        "1c",
        "0m",
        "0d",
        "1s",
        "$end",
    ]

    last_time = None
    for time_us, clk, mosi, dc, cs in trace.events:
        if time_us != last_time:
            lines.append(f"#{time_us}")
            last_time = time_us
        lines.append(f"{clk}c")
        lines.append(f"{mosi}m")
        lines.append(f"{dc}d")
        lines.append(f"{cs}s")

    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_csv(path: Path, trace: DigitalTrace) -> None:
    sample_period_us = 1_000_000 / trace.sample_rate_hz
    total_samples = int(trace.time_us / sample_period_us) + 1

    event_index = 0
    clk = trace.events[0][1]
    mosi = trace.events[0][2]
    dc = trace.events[0][3]
    cs = trace.events[0][4]

    with path.open("w", encoding="ascii", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["time_us", "CLK", "MOSI", "DC", "CS"])
        for sample in range(total_samples):
            time_us = round(sample * sample_period_us, 6)
            while (
                event_index + 1 < len(trace.events)
                and trace.events[event_index + 1][0] <= time_us
            ):
                event_index += 1
                _, clk, mosi, dc, cs = trace.events[event_index]
            writer.writerow([time_us, clk, mosi, dc, cs])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sample-rate", type=int, default=1_000_000)
    parser.add_argument("--spi-rate", type=int, default=100_000)
    parser.add_argument("--gap-ms", type=int, default=500)
    parser.add_argument("--prefix", default="ssd1306_spi_blink")
    parser.add_argument("--out-dir", type=Path, default=Path(__file__).resolve().parent)
    args = parser.parse_args()

    trace = generate_trace(args.sample_rate, args.spi_rate, args.gap_ms)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    vcd_path = args.out_dir / f"{args.prefix}.vcd"
    csv_path = args.out_dir / f"{args.prefix}.csv"
    write_vcd(vcd_path, trace)
    write_csv(csv_path, trace)

    print(f"Generated {vcd_path}")
    print(f"Generated {csv_path}")
    print(f"Duration: {trace.time_us} us")


if __name__ == "__main__":
    main()
